---
- hosts: sandbox_routers
  name: Verify Interfaces on Cisco IOS XE
  connection: network_cli
  tasks:

    - name: Display interfaces on Cisco IOS XE
      ios_command:
        commands: show interfaces description
      register: interfaces
    - debug: msg="{{ interfaces.stdout_lines }}"

    - name: Display interface runnning config
      ios_command:
        commands: show run int Gi1 | begin ^interface
      register: interfaces
    - debug: msg="{{ interfaces.stdout_lines }}"


    - name: Display interface statistics
      ios_command: 
        commands: show interface Gi1 | include error|CRC|TX|RX|Description|discard|Last
      register: interfaces
    - debug: msg="{{ interfaces.stdout_lines }}"
