---
- hosts: sandbox_routers
  name: Verify Interfaces on Cisco IOS XE
  connection: network_cli
  tasks:
    - name: Display interfaces on Cisco IOS XE
      ios_command:
        commands: 
            - show ip interface brief
            - show interface description
            - show run int gi1
            - show int gi1
            - show ip route
      register: interfaces
    - debug: 
        msg: "{{ interfaces.stdout_lines }}"
       
