#!/usr/bin/env python

from netmiko import ConnectHandler
from pprint import pprint

iosv_l2_s1 = {
    'device_type': 'cisco_ios',
    'ip': '192.68.48.1',
    'username': '****',
    'password': '****',
}

print('Sending command 1')
net_connect = ConnectHandler(**iosv_l2_s1)
output = net_connect.send_command('show crypto isakmp sa')
print(output)

print('Sending command 2')
net_connect = ConnectHandler(**iosv_l2_s1)
output = net_connect.send_command('show crypto session detail', use_textfsm=True)

pprint(output)

